// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjZJrjGkjrYdKWBNP2VuxTLMXQRZsB1ws',
    appId: '1:389736651575:web:96f6da30ed0bd5f400d8b2',
    messagingSenderId: '389736651575',
    projectId: 'localink-778c5',
    authDomain: 'localink-778c5.firebaseapp.com',
    storageBucket: 'localink-778c5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaRdWEmEijKLDStEKnJLjhRPT_Ok1XK4M',
    appId: '1:389736651575:android:62b1e927186e2e5000d8b2',
    messagingSenderId: '389736651575',
    projectId: 'localink-778c5',
    storageBucket: 'localink-778c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdHWMVC-sRXuQkQhYzgmVMcwv9otlSiOY',
    appId: '1:389736651575:ios:b34e564d2c23d01500d8b2',
    messagingSenderId: '389736651575',
    projectId: 'localink-778c5',
    storageBucket: 'localink-778c5.appspot.com',
    iosBundleId: 'com.company.localinkSm',
  );
}
